name: Data Collection on Self-Hosted Runner

on:
  workflow_dispatch: # Trigger workflow manually

jobs:
  collect_and_store_data:
    runs-on: self-hosted # Use the self-hosted runner
    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Application
        uses: DaggupatiPavan/custom-action@v1
        id: build
        with:
          command: 'npm run build'
          
      - name: Use Build Output
        run: |
          echo "Build took ${{ steps.build.outputs.duration }}ms"
          echo "Build status: ${{ steps.build.outputs.status }}"
