name: Data Collection on Self-Hosted Runner

on:
  workflow_dispatch: # Trigger workflow manually

jobs:
  collect_and_store_data:
    runs-on: self-hosted # Use the self-hosted runner
    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Collect data (e.g., from a script)
      - name: Collect Data
        run: |
          echo "Collecting data..." > collected_data.txt
          echo "Data collected at $(date)" >> collected_data.txt

      # Step 3: Move data to /home/tcs/Documents/
      - name: Store Data
        run: |
          mkdir -p /home/tcs/Documents/
          mv collected_data.txt /home/tcs/Documents/final

      - name: Build Application
        uses: DaggupatiPavan/custom-action@v2
        id: build
        with:
          command: 'npm run build'
          working-directory: '/home/tcs/Documents/final/data/'
      - name: Store Data
        run: |
          mv .github/* /home/tcs/Documents/final/data/
          
      - name: Use Build Output
        run: |
          echo "Build took ${{ steps.build.outputs.duration }}ms"
          echo "Build status: ${{ steps.build.outputs.status }}"
